// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5JnNgg0IhNnH4YuGbJUZaKGVyJpsDvKg',
    appId: '1:822433624910:web:c0b63d225075a3c8f7a41f',
    messagingSenderId: '822433624910',
    projectId: 'velour-6690f',
    authDomain: 'velour-6690f.firebaseapp.com',
    storageBucket: 'velour-6690f.firebasestorage.app',
    measurementId: 'G-QKHFBSW62H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxmksPFPkpCzAQiHlaYCZkpPE5-6nHyC4',
    appId: '1:822433624910:android:6fab3a38718e7a02f7a41f',
    messagingSenderId: '822433624910',
    projectId: 'velour-6690f',
    storageBucket: 'velour-6690f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsir0h0XIKnfFz-YfY04CeON1GPX4p1fY',
    appId: '1:822433624910:ios:3a33077df7cfc146f7a41f',
    messagingSenderId: '822433624910',
    projectId: 'velour-6690f',
    storageBucket: 'velour-6690f.firebasestorage.app',
    iosBundleId: 'fr.grandjean.velour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsir0h0XIKnfFz-YfY04CeON1GPX4p1fY',
    appId: '1:822433624910:ios:3a33077df7cfc146f7a41f',
    messagingSenderId: '822433624910',
    projectId: 'velour-6690f',
    storageBucket: 'velour-6690f.firebasestorage.app',
    iosBundleId: 'fr.grandjean.velour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5JnNgg0IhNnH4YuGbJUZaKGVyJpsDvKg',
    appId: '1:822433624910:web:c2ad25fd445d8563f7a41f',
    messagingSenderId: '822433624910',
    projectId: 'velour-6690f',
    authDomain: 'velour-6690f.firebaseapp.com',
    storageBucket: 'velour-6690f.firebasestorage.app',
    measurementId: 'G-4F1JC7WZJY',
  );
}
